name = "cmart073"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "cmart073-db"
database_id = "fc0cb680-e30c-408b-b60e-f13f42e57010"

[[r2_buckets]]
binding = "R2"
bucket_name = "cmart073-uploads"

